# Generated by Django 6.0 on 2025-12-07 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AddField(
            model_name="expense",
            name="bank",
            field=models.CharField(
                blank=True,
                help_text="Source bank or account, e.g. 'Sberbank', 'T-Bank', 'Manual'.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(default="RUB", max_length=3),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
